* Gnorb

Glue code between the Gnus, Org, and BBDB packages for Emacs.

This package connects Emacs-based email, project management, and
contact management a little more closely together. The goal is to
reduce friction when manipulating TODOs, contacts, messages, and
files. An underlying principle is that one should stay in the Org
Agenda as much as possible: Gnus should serve as input/output for the
Agenda, and BBDB should serve as an alternate view on information.
This isn't actually enforced, of course, it's just an ideal.

Put "gnorb/lisp" in your load path, then either require "gnorb" to
load everything, or pick bits and pieces: "gnorb-gnus", "gnorb-org",
or "gnorb-bbdb".

Recommended keybindings/integration measures are shown below. Copy
them into your init files and edit as you see fit.

Code in this package is aimed at the development (git) versions of
Gnus, Org, and BBDB (that means BBDB 3: upgrade, already!). I'll try
to make it work with the most recent stable releases of those
packages, but I'm not promising anything.

Most of the functions listed later in this README are fairly discrete:
they do one thing only, and (I hope) don't require anything special in
terms of file formats or workflow. A few exceptions to that are listed
below.
** Using Gnorb for Tracking Email TODOs

Tracking correspondences between Org TODOs and email messages is one
of the more complicated things that Gnorb does, and thus requires a
little setup. Tracking relies on the Gnus registry, so that must be
installed (ie you've called `gnus-registry-initialize' somewhere). It
also relies on Org ids, so you'll want to require 'org-id, and set
`org-id-track-globally' to t (that's the default anyway).

Once that's done, call `gnorb-tracking-initialize' after loading
Gnorb.

In addition, Gnorb can provide the very useful service of opening nnir
*Summary* buffers containing all the messages linked to from a given
subtree, see [[id:89ec2ade-5686-402e-a23c-2af36325d1f3][Showing gnus messages from links in Org buffers]] below.

NOTE: If you were using an earlier version of Gnorb that stored
correspondences in Org properties, you can transition to the newer
system with the function `gnorb-registry-transition-from-props'. See
the docstring for details.

*** Capture templates for emails
Most people will be using plain capture templates to create TODOs from
messages. When the TODO is made, Gnorb will record the connection
between the message and the TODO, using the Gnus registry. Later, you
can call `gnorb-org-handle-mail' on the TODO: Gnorb will find the
associated message and start a reply to it.

If you've made a TODO that doesn't have any messages associated with
it yet (for instance, a TODO reminding you to email someone), then
Gnorb will look for gnus:, mailto:, or bbdb: links in the subtree, and
act on them accordingly.

The option `gnorb-org-mail-scan-scope' determines how many paragraphs
of the subtree will be scanned for links. 0 means only the heading
text, a positive integer means the heading plus that many paragraphs
of body text, and any other non-nil value means the whole subtree will
be scanned.

Your capture templates should therefore put links where
`gnorb-org-handle-mail' can find them. Say your capture template looks
like this:

#+BEGIN_SRC emacs-lisp
  '("r" "Work-related Reply" entry (file+headline "~/org/job.org" "Emails")
    "** REPLY %:fromname\n%?Received on %:date-timestamp-inactive, link: %a"
    :gnus-attachments t)

#+END_SRC

In this case, you'll want to set `gnorb-org-mail-scan-scope' to at
least 1, to scan the first paragraph of body text.

The same goes for "remind me to email so-and-so" TODOs. The mailto: or
bbdb: link pointing at so-and-so should be located where
`gnorb-org-handle-mail' can find it.

In fact, you can use any Org TODO as a starting point for
`gnorb-org-handle-mail'. Gnorb will do its best to find mail-related
information from the subtree, but if it can't it will simply start
composing a blank message. When the message is sent, it will be
associated with the TODO.

*** Tracking conversations
You can use Gnorb to remind you to reply to a message, to track
extended email conversations, or to manage complex email-centric
projects.

The principle is simple: Incoming and outgoing messages are all
associated with an Org heading, or its sub-headings. Outgoing messages
are created by calling `gnorb-org-handle-mail' on an Org TODO, which
starts a reply or a new message, depending on the state of the TODO.
Incoming messages are associated with TODOs by calling
`gnorb-gnus-incoming-do-todo' on the message, and choosing the TODO.

In both cases, you'll be asked to "trigger an action" on the TODO in
question. Actions including changing TODO state (and associating the
message with the TODO), taking a note (and associating the message),
just associating the message, and doing nothing at all. We're also
planning trigger actions that will capture new headings as children or
siblings of the original TODO, but that's not done yet. You can also
provide your own actions.

In this way, a single TODO collects an entire conversation of emails.
If you have subtrees as a part of the original TODO, each subtree has
its own collection of emails, which are inherited by the parent. To
view all these messages in a single Gnus *Summary* buffer, see [[id:89ec2ade-5686-402e-a23c-2af36325d1f3][Showing
gnus messages from links in Org buffers]] below.
*** Hinting in Gnus
When you receive new mails that might be relevant to existing Org
TODOs, Gnorb can alert you to that fact. When
`gnorb-gnus-hint-relevant-article' is t (the default), Gnorb will
display a message in the minibuffer when opening potentially relevant
messages. You can then use `gnorb-gnus-incoming-to-todo' to trigger an
action on the relevant TODO.

This hinting can happen in the Gnus summary buffer as well. If you use
the escape indicated by `gnorb-gnus-summary-mark-format-letter" as
part of your `gnus-summary-line-format', articles that are relevant to
TODOs will be marked with a special character in the Summary buffer,
as determined by `gnorb-gnus-summary-mark'. By default, the format
letter is "g" (meaning it is used as "%ug" in the format line), and
the mark is "ยก".
** Showing gnus messages from links in Org buffers
:PROPERTIES:
:ID:       89ec2ade-5686-402e-a23c-2af36325d1f3
:END:
Sometimes you've got an Org subtree tracking many relevant Gnus
messages, and you'd like to see all those message in a single Gnus
summary buffer. Gnorb can do this, but you'll have to add a new
backend to your list of Gnus servers. If that makes your skin crawl a
little, it probably should. But no fear! The server essentially does
nothing but provide a place for nnir to hang searches.

Add an entry like this to your `gnus-secondary-select-methods':

(nngnorb "Purely Decorative Server Name")

And restart Gnus. Now, on any given Org subtree, you can call
`gnorb-org-view', and you'll be presented with an nnir Summary buffer
containing all the messages connected to the subtree. If you reply to
any messages from this buffer, your reply will also be tracked as part
of the subtree.

As a bonus, it's possible to go into Gnus' *Server* buffer, find the
line specifying your nngnorb server, and hit "G" (aka
`gnus-group-make-nnir-group'). At the query prompt, enter an Org-style
tags-todo Agenda query string (eg "+work-computer", or what have you).
Gnorb will find all headings matching this query, scan their subtrees
for gnus links, and then give you a Summary buffer containing all the
linked messages. This is dog-slow at the moment; it will get faster.
** Recent mails from BBDB contacts
If you're using a recent git version of BBDB (circa mid-May 2014 or
later), you can give your BBDB contacts a special field which will
collect links to recent emails from that contact. The default name of
the field is "messages", but you can customize that name using the
`gnorb-bbdb-messages-field' option.

Gnorb will not collect links by default: you need to call
`gnorb-bbdb-open-link' on a contact once to start the process.
Thereafter, opening mails from that contact will store a link to the
message.

Once some links are stored, `gnorb-bbdb-open-link' will open them: Use
a prefix arg to the function call to select particular messages to
open. There are several options controlling how all this works; see
the gnorb-bbdb user options section below for details.
** BBDB posting styles
Gnorb comes with a BBDB posting-style system, inspired by (copied
from) gnus-posting-styles. You can specify how messages are composed
to specific contacts, by matching on contact field values (the same
way gnus-posting-styles matches on group names). See the docstring of
`gnorb-bbdb-posting-styles' for details.

In order not to be too intrusive, Gnorb doesn't alter the behavior of
`bbdb-mail', the usual mail-composition function. Instead it provides
an alternate `gnorb-bbdb-mail', which does exactly the same thing, but
first processes the new mail according to `gnorb-bbdb-posting-styles'.
If you want to use this feature regularly, you can rebind "m" in
`bbdb-mode-map' to `gnorb-bbdb-mail'.
** Using attach with org capture
Set the new :gnus-attachments key to "t" in a capture template that
you use on mail messages, and you'll be queried to re-attach the
message's attachments onto the newly-captured heading. Or set
`gnorb-gnus-capture-always-attach' to "t" to have Gnorb do this for
all capture templates.
** Restoring window layout
Many Gnorb functions alter the window layout and value of point. In
most of these cases, you can restore the previous layout using the
interactive function `gnorb-restore-layout'.
** Gnorb-BBDB
*** Interactive Functions
**** gnorb-bbdb-tag-agenda
Give BBDB records an org-tag field (customizable), then call this
function on the current records(s) to open an Org agenda tags search
using those tags. Only shows TODOs by default: use a prefix argument
to show all tagged headings.
**** gnorb-bbdb-mail-search
Search for all mail messages from the record(s) displayed. Currently
supports the notmuch, mairix, and namazu search backends; set
`gnorb-gnus-mail-search-backend' to one of those symbol values.
**** gnorb-bbdb-cite-contact
Prompt for a BBDB record and insert a string of the type "Bob Smith
<bob@smith.com>".
**** gnorb-bbdb-mail
Exactly like `bbdb-mail', except it runs the records through
`gnorb-bbdb-posting-styles' first, and alters the composed message
accordingly.
**** gnorb-bbdb-open-link
Open a message linked to from within a BBDB record's
`gnorb-bbdb-messages-field'. Use prefix args to select the exact
message. If a record is not yet collecting links, use this function to
start the collection process.
*** User Options
**** gnorb-bbdb-org-tag-field
The name of the BBDB xfield that holds Org-related tags. Specified as
a string with the ":" separator between tags, same as for Org
headings. Defaults to 'org-tag.
**** gnorb-bbdb-messages-field
The name of the BBDB xfield that holds links to recently-received
messages from this contact. Defaults to 'messages.
**** gnorb-bbdb-collect-N-messages
Collect at most this many links to messages from this contact.
Defaults to 5.
**** gnorb-bbdb-define-recent
What does "recently-received" mean? Possible values are 'seen and
'received. When set to 'seen, the most recently-opened messages are
collected. When set to 'received, the most recently-received (by Date
header) messages are collected. Defaults to 'seen.
**** gnorb-bbdb-message-link-format-multi
How is a single message's link formatted in the multi-line BBDB layout
format? Defaults to "%:count. %D: %:subject" (see the docstring for
details).
**** gnorb-bbdb-message-link-format-one
How is a single message's link formatted in the one-line BBDB layout
format? Defaults to nil (see the docstring for details).
**** gnorb-bbdb-posting-styles
Styles to use for influencing the format of mails composed to the BBDB
record(s) under point (see the docstring for details).
*** Suggested Keybindings
#+BEGIN_SRC emacs-lisp
  (eval-after-load "gnorb-bbdb"
    '(progn
       (define-key bbdb-mode-map (kbd "O") 'gnorb-bbdb-tag-agenda)
       (define-key bbdb-mode-map (kbd "S") 'gnorb-bbdb-mail-search)
       (define-key bbdb-mode-map (kbd "m") 'gnorb-bbdb-mail)
       (define-key bbdb-mode-map (kbd "l") 'gnorb-bbdb-open-link)
       (global-set-key (kbd "C-c C") 'gnorb-bbdb-cite-contact)))
#+END_SRC
** Gnorb-Org
*** Functions
**** gnorb-org-contact-link
Prompt for a BBDB record and insert a link to that record at
point.
**** gnorb-org-handle-mail
This function does its best to interpret the heading under point as an
email action.

If the heading text contains a link to a Gnus message then start a
reply to that message, otherwise start composing a new message. If the
heading contains mailto links or BBDB links, put those addresses in
the "To" field of the new message (or reply). If the heading has
org-attach'ed attachments, prompt to attach them to the outgoing
message.

When the message is sent, return to the original Org buffer. If the
heading's TODO keyword is a member of `gnorb-org-mail-todos' (by
default, "MAIL" and "REPLY"), then call `org-agenda-todo' and prompt
to mark the TODO as done. Set that option to nil to prompt for all
TODO keywords.

This works best with a matching capture template: the template stores
a link to the message under point within the headline text, and this
command replies to that message in a DWIM style.

**** gnorb-org-email-subtree
Call on a Org subtree to export the subtree as either text or a file.
Then compose a message with the text in the message body, or the file
attached to the message. See the `gnorb-org-email-subtree-*' user
options for influencing this process.

There's a little overlap with org-mime, but this function allows for
exporting the subtree as a file, and does not compose a MIME-multipart
HTML message. I may look into integrating it a bit with org-mime
later.

This function also overlaps with `gnorb-org-handle-mail'. The only
difference is that it will first prompt to export the subtree of the
heading under point. After that, it behaves much like
`gnorb-org-handle-mail'.

Use `gnorb-org-handle-mail' when the primary purpose of the heading is
as a TODO reminding you to send or reply to an email. Any text under
the heading will be disregarded.

Use `gnorb-org-email-subtree' when the primary purpose of the heading
is the text (or tables or lists or...) of its subtree, and you just
happen to want to email that content to someone.

**** gnorb-org-popup-bbdb
Pop up a BBDB buffer relevant to the current Org display. This works
differently depending on whether you're in the Agenda, or in a regular
Org file.

In an Agenda buffer currently displaying an `org-tags-view' search (ie
called with the "m" or "M" keys), it will look through your BBDB
database and pop up a BBDB buffer displaying all records that match
the current tags search.

In a regular file, it will look at the heading under point for bbdb:
links, and pop up a BBDB buffer showing those records.
**** gnorb-org-view
If you've got a 'nngnorb backend installed in your gnus select
methods, you can use this function on a subtree to scan it for gnus
links and open all linked messages in a nnir summary buffer.
*** User Options
**** gnorb-org-mail-scan-strategies
This option provides various strategies for how the
`gnorb-org-handle-mail' and `gnorb-org-email-subtree' functions act on
links within the subtree at point. Three different options are
provided, for flexibility -- see the docstring for details.
**** gnorb-org-capture-collect-link-p
When this is set to t, the capture process will always store a link to
the Gnus message or BBDB record under point, even when the link isn't
part of the capture template. It can then be added to the captured
heading with org-insert-link, as usual.
**** gnorb-org-agenda-popup-bbdb
Set to t to automatically pop up the BBDB buffer displaying records
corresponding to the Org Agenda tags search underway. If this is nil
you can always do it manually with the command of the same name.
**** gnorb-org-bbdb-popup-layout
Controls the layout of the Agenda-related BBDB popup, takes the same
values as bbdb-pop-up-layout.
*** Suggested Keybindings
#+BEGIN_SRC emacs-lisp
  (eval-after-load "gnorb-org"
    '(progn
       (org-defkey org-mode-map (kbd "C-c C") 'gnorb-org-contact-link)
       (org-defkey org-mode-map (kbd "C-c H") 'gnorb-org-handle-mail)
       (org-defkey org-mode-map (kbd "C-c e") 'gnorb-org-view)
       (org-defkey org-mode-map (kbd "C-c E") 'gnorb-org-email-subtree)
       (org-defkey org-mode-map (kbd "C-c V") 'gnorb-org-popup-bbdb)
       (setq gnorb-org-agenda-popup-bbdb t)
       (eval-after-load "org-agenda"
         '(progn (org-defkey org-agenda-mode-map (kbd "H") 'gnorb-org-handle-mail)
                 (org-defkey org-agenda-mode-map (kbd "V") 'gnorb-org-popup-bbdb)))))
#+END_SRC
** Gnorb-Gnus
*** Functions
**** gnorb-gnus-article-org-attach
When called on an email with attached files, prompt for an Org heading
and attach the files to that heading using org-attach.
**** gnorb-gnus-incoming-do-todo
Call on an incoming message that should trigger a state change or a
note on an existing TODO. You'll be asked to locate the appropriate
TODO, and the action will depend in part on the value of
`gnorb-gnus-message-trigger-default', which see. If the incoming
message refers to messages that are already tracked in a conversation,
Gnorb will prompt you with the relevant TODO.
**** gnorb-gnus-outgoing-do-todo
Call this while composing a new message (ie in message-mode), or
immediately after sending a message. If the message is a new one (ie
it's not part of an email conversation that's already being tracked) a
new TODO will be made from it. This is handy when you need to make
sure you get a response, for instance. New TODOs are created using the
capture process, and you'll need to specify a capture template to use
for outgoing messages: see `gnorb-gnus-new-todo-capture-key'.

If you call this on a message that's part of an already-tracked
conversation, you'll be prompted to change TODO state or leave a note
on that conversation.
*** User Options
**** gnorb-gnus-mail-search-backend
Specifies the search backend that you use for searching mails.
Currently supports notmuch, mairix, and namazu: set this option to one
of those symbols.
**** gnorb-gnus-capture-always-attach
Treat all capture templates as if they had the :gnus-attachments key
set to "t". This only has any effect if you're capturing from a Gnus
summary or article buffer.
**** gnorb-trigger-todo-default
Set to either 'note or 'todo to tell `gnorb-gnus-incoming-do-todo'
what to do by default. You can reach the non-default behavior by
calling that function with a prefix argument. Alternately, set to
'prompt to always prompt for the appropriate action.
**** gnorb-gnus-trigger-refile-targets
If you use `gnorb-gnus-incoming-do-todo' on an incoming message, Gnorb
will try to locate a TODO heading that's relevant to that message. If
it can't, it will prompt you for one, using the refile interface. This
option will be used as the value of `org-refile-targets' during that
process: see the docstring of `org-refile-targets' for the appropriate
syntax.
**** gnorb-gnus-new-todo-capture-key
Set this to a single-character string pointing at an Org capture
template to use when creating TODOs from outgoing messages. The
template is a regular capture template, with a few exceptions. If Gnus
helps you archive outgoing messages (ie you have
`gnus-message-archive-group' set to something, and your outgoing
messages have a "Fcc" header), a link to that message will be made,
and you'll be able to use all the escapes related to gnus messages. If
you don't archive outgoing messages, you'll still be able to use the
%:subject, %:to, %:toname, %:toaddress, and %:date escapes in the
capture template.
**** gnorb-gnus-hint-relevant-article
Set to "t" (the default) to have Gnorb give you a hint in the
minibuffer when opening messages that might be relevant to existing
Org TODOs.
**** gnorb-gnus-summary-mark-format-letter
The formatting letter to use as part of your
`gnus-summary-line-format', to indicate messages which might be
relevant to Org TODOs. Defaults to "g", meaning it should be used as
"%ug" in the format line.
**** gnorb-gnus-summary-mark
The mark used to indicate relevant messages in the Summary buffer,
when `gnorb-gnus-summary-mark-format-letter' is present in the format
line. Defaults to "ยก".
*** Suggested Keybindings
#+BEGIN_SRC emacs-lisp
  (eval-after-load "gnorb-gnus"
    '(progn
       (define-key gnus-summary-mime-map "a" 'gnorb-gnus-article-org-attach)
       (define-key gnus-summary-mode-map (kbd "C-c t") 'gnorb-gnus-incoming-do-todo)
       (push '("attach to org heading" . gnorb-gnus-mime-org-attach)
             gnus-mime-action-alist)
       ;; The only way to add mime button command keys is by redefining
       ;; gnus-mime-button-map, possibly not ideal. Ideal would be a
       ;; setter function in gnus itself.
       (push '(gnorb-gnus-mime-org-attach "a" "Attach to Org heading")
             gnus-mime-button-commands)
       (setq gnus-mime-button-map
             (let ((map (make-sparse-keymap)))
               (define-key map gnus-mouse-2 'gnus-article-push-button)
               (define-key map gnus-down-mouse-3 'gnus-mime-button-menu)
               (dolist (c gnus-mime-button-commands)
                 (define-key map (cadr c) (car c)))
               map))))

  (eval-after-load "message"
    '(progn
       (define-key message-mode-map (kbd "C-c t") 'gnorb-gnus-outgoing-do-todo)))
#+END_SRC
** Wishlist TODO
- Support adding X-Org-Id headers to Gnus messages, which point at
  relevant Org headings (possibly not really useful).
- Provide a command that, when in the Org Agenda, does an email search
  for messages received in the visible date span, or day under point,
  etc. Make it work in the calendar, as well?
- Look into message tagging in Gnus -- what are the options? Is it
  possible to search for tagged messages when we do an Org agenda tag
  search?
- Allow automatic org-tagging of BBDB contacts: when messages from a
  contact are associated with an Org heading, make it possible for the
  contact to inherit that heading's tags.
